import {
  AlertTriangle,
  ArrowUpCircle,
  Calendar,
  Clock,
  Code,
  Container,
  FileWarning,
  FolderTree,
  GitBranch,
  Globe,
  Key,
  Layers,
  Lightbulb,
  Package,
  RefreshCw,
  Scale,
  Server,
  Shield,
  ShieldAlert,
  ShieldX,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Zap,
} from 'lucide-react'

export const priorityConfig = {
  critical: { color: 'bg-severity-critical', textColor: 'text-severity-critical', label: 'Critical' },
  high: { color: 'bg-severity-high', textColor: 'text-severity-high', label: 'High' },
  medium: { color: 'bg-severity-medium', textColor: 'text-severity-medium', label: 'Medium' },
  low: { color: 'bg-severity-low', textColor: 'text-severity-low', label: 'Low' },
}

export const typeConfig: Record<string, { icon: typeof Container; label: string; color: string; bgColor: string }> = {
  base_image_update: {
    icon: Container,
    label: 'Base Image Update',
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
  },
  direct_dependency_update: {
    icon: Package,
    label: 'Dependency Update',
    color: 'text-success',
    bgColor: 'bg-success/10',
  },
  transitive_fix_via_parent: {
    icon: Layers,
    label: 'Transitive Fix',
    color: 'text-purple-500',
    bgColor: 'bg-purple-500/10',
  },
  no_fix_available: {
    icon: ShieldX,
    label: 'No Fix Available',
    color: 'text-gray-500',
    bgColor: 'bg-gray-500/10',
  },
  consider_waiver: {
    icon: Shield,
    label: 'Consider Waiver',
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
  },
  rotate_secrets: {
    icon: Key,
    label: 'Rotate Secrets',
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
  },
  remove_secrets: {
    icon: FileWarning,
    label: 'Remove Secrets',
    color: 'text-severity-high',
    bgColor: 'bg-severity-high/10',
  },
  fix_code_security: {
    icon: Code,
    label: 'Fix Code Issues',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
  },
  fix_infrastructure: {
    icon: Server,
    label: 'Fix Infrastructure',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
  },
  license_compliance: {
    icon: Scale,
    label: 'License Compliance',
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
  },
  supply_chain_risk: {
    icon: AlertTriangle,
    label: 'Supply Chain Risk',
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-500/10',
  },
  outdated_dependency: {
    icon: Clock,
    label: 'Outdated Dependency',
    color: 'text-amber-600',
    bgColor: 'bg-amber-600/10',
  },
  version_fragmentation: {
    icon: GitBranch,
    label: 'Version Fragmentation',
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
  },
  dev_in_production: {
    icon: Sparkles,
    label: 'Dev in Production',
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
  },
  unmaintained_package: {
    icon: Calendar,
    label: 'Unmaintained Package',
    color: 'text-gray-600',
    bgColor: 'bg-gray-600/10',
  },
  recurring_vulnerability: {
    icon: RefreshCw,
    label: 'Recurring Issue',
    color: 'text-rose-500',
    bgColor: 'bg-rose-500/10',
  },
  regression_detected: {
    icon: TrendingDown,
    label: 'Regression Detected',
    color: 'text-red-600',
    bgColor: 'bg-red-600/10',
  },
  deep_dependency_chain: {
    icon: FolderTree,
    label: 'Deep Dependency Chain',
    color: 'text-slate-500',
    bgColor: 'bg-slate-500/10',
  },
  duplicate_functionality: {
    icon: Layers,
    label: 'Duplicate Functionality',
    color: 'text-fuchsia-500',
    bgColor: 'bg-fuchsia-500/10',
  },
  cross_project_pattern: {
    icon: Globe,
    label: 'Cross-Project Pattern',
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
  },
  shared_vulnerability: {
    icon: Globe,
    label: 'Shared Vulnerability',
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
  },
  critical_hotspot: {
    icon: Zap,
    label: 'Critical Hotspot',
    color: 'text-red-600',
    bgColor: 'bg-red-600/20',
  },
  known_exploit: {
    icon: ShieldAlert,
    label: 'Known Exploit (KEV)',
    color: 'text-destructive',
    bgColor: 'bg-destructive/20',
  },
  ransomware_risk: {
    icon: ShieldX,
    label: 'Ransomware Risk',
    color: 'text-red-700',
    bgColor: 'bg-red-700/20',
  },
  actively_exploited: {
    icon: TrendingUp,
    label: 'High Exploit Probability',
    color: 'text-orange-600',
    bgColor: 'bg-orange-600/20',
  },
  malware_detected: {
    icon: ShieldX,
    label: 'Malware Detected',
    color: 'text-red-800',
    bgColor: 'bg-red-800/20',
  },
  typosquat_detected: {
    icon: AlertTriangle,
    label: 'Typosquatting',
    color: 'text-amber-600',
    bgColor: 'bg-amber-600/20',
  },
  hash_mismatch: {
    icon: Shield,
    label: 'Hash Mismatch',
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
  },
  eol_dependency: {
    icon: Clock,
    label: 'End-of-Life',
    color: 'text-gray-600',
    bgColor: 'bg-gray-600/20',
  },
  quick_win: {
    icon: Lightbulb,
    label: 'Quick Win',
    color: 'text-green-600',
    bgColor: 'bg-green-600/20',
  },
  single_update_multi_fix: {
    icon: ArrowUpCircle,
    label: 'Multi-Fix Update',
    color: 'text-success',
    bgColor: 'bg-success/20',
  },
  toxic_dependency: {
    icon: AlertTriangle,
    label: 'Toxic Dependency',
    color: 'text-purple-600',
    bgColor: 'bg-purple-600/20',
  },
  attack_surface_reduction: {
    icon: Shield,
    label: 'Reduce Attack Surface',
    color: 'text-blue-600',
    bgColor: 'bg-blue-600/10',
  },
  critical_risk: {
    icon: ShieldAlert,
    label: 'Critical Risk',
    color: 'text-destructive',
    bgColor: 'bg-destructive/10',
  },
}

export const effortConfig = {
  low: { label: 'Low Effort', color: 'text-success' },
  medium: { label: 'Medium Effort', color: 'text-severity-medium' },
  high: { label: 'High Effort', color: 'text-severity-critical' },
}
