sonar.projectKey=morzan1001_Dependency-Control
sonar.organization=morzan1001

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/htmlcov/**,**/dist/**
