from collections.abc import Iterable

from app.core.security import create_access_token
from app.models.user import User
from tests.helpers.permission_presets import PRESET_ADMIN


def bearer_headers(user_id: str, permissions: Iterable[str]) -> dict[str, str]:
    return {"Authorization": f"Bearer {create_access_token(user_id, permissions=list(permissions))}"}


def make_admin() -> User:
    return User(id="admin-1", username="admin", email="admin@test.com", permissions=list(PRESET_ADMIN))


# Minted by python-jose 3.5.0 with the test SECRET_KEY; tokens issued before the PyJWT switch must still decode.
JOSE_SUBJECT_ID = "64b7f0c2a1b2c3d4e5f60718"
JOSE_SUBJECT_EMAIL = "legacy.user@example.com"
JOSE_RESET_PASSWORD_HASH = "$argon2id$v=19$m=65536,t=3,p=4$legacyhash"
JOSE_TOKENS = {
    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTE5MDA5LCJzdWIiOiI2NGI3ZjBjMmExYjJjM2Q0ZTVmNjA3MTgiLCJ0eXBlIjoiYWNjZXNzIiwianRpIjoiYWQwYjUwNWUtZDIwNi00ZmQ3LThlYzUtZTEwYjkwNjdhZTM2IiwicGVybWlzc2lvbnMiOlsicHJvamVjdDpyZWFkIiwic3lzdGVtOm1hbmFnZSJdfQ.cOPe3XBdv7SijUqjn3I8iQQzz27UnIiXCruNtH947Z4",
    "access_setup_2fa": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTQwNTUsInN1YiI6IjY0YjdmMGMyYTFiMmMzZDRlNWY2MDcxOCIsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiJhODAwMGRiYS1lOTkyLTRjMGQtOGM4OC1lY2E3ZmNiZWNiOGMiLCJwZXJtaXNzaW9ucyI6WyJhdXRoOnNldHVwXzJmYSJdfQ.PHTR41s3bn5d_gPGI9Xq33YlgoHNIHCRmtsvawPs6Uk",
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA4ODI0MjAsImlhdCI6MTc5MTIxODQyMC4wNTQwOTcsInN1YiI6IjY0YjdmMGMyYTFiMmMzZDRlNWY2MDcxOCIsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiNGJmZmY0MmQtZDZmYS00ZGY0LThhYWUtM2QyYmZhNTJhZTkzIn0.obcjpiHeKRjH0b8Ou8aQp_gLRs9A2CEmGbqSEbLC7TM",
    "email_verification": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTQxMjIsInN1YiI6ImxlZ2FjeS51c2VyQGV4YW1wbGUuY29tIiwidHlwZSI6ImVtYWlsX3ZlcmlmaWNhdGlvbiIsImp0aSI6IjFjNGRhYzFjLTQ1NDItNDFjNi1hMWU2LWVlNGRhOTdmMTFmMSJ9.9RV28Ql0uZZKFpYyh3PmaVbet8Wvwr81G2kx2TG9TLk",
    "password_reset": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTQxNTkyLCJzdWIiOiJsZWdhY3kudXNlckBleGFtcGxlLmNvbSIsInR5cGUiOiJwYXNzd29yZF9yZXNldCIsImp0aSI6IjVlNWIyODRjLWY1NmYtNDNjNC05MGE0LTMxYmZiNGYxNDM0MCIsInB3ZiI6Ijk5ZWYyMmY3N2EyODEzNDcifQ.l12w7BmqL0g43VJ5lpa43rtm7yjSfWZTGUH7BfhhBk4",
    "email_change": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTQxNzksInN1YiI6IjY0YjdmMGMyYTFiMmMzZDRlNWY2MDcxOCIsInR5cGUiOiJlbWFpbF9jaGFuZ2UiLCJqdGkiOiI1NmU2ZTczNy04MzliLTQ2Y2UtYTE1Yi1lOGM1ZGIzMmNkNTkiLCJlbWFpbCI6Im5ldy5hZGRyZXNzQGV4YW1wbGUuY29tIn0.rzLEQyXGwNt3mWJL44BXuBS651VHKmyB6-NZvcCDF_k",
    "slack_oauth": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQwNzA5MDc2MjAsImlhdCI6MTc5MTIxODQyMC4wNTQxOTYsInN1YiI6IjY0YjdmMGMyYTFiMmMzZDRlNWY2MDcxOCIsInR5cGUiOiJzbGFja19vYXV0aCIsImp0aSI6ImY3YWQ0YzEzLTliYmItNDM3Zi04OGZjLTRiMDA2YzhmZDRhZCJ9.uRLElxzeSNft0BRdMJqI4IIWWyK5sw9Oj-veJTbzJ2A",
}
