"""Framework inputs shaped the way ComplianceReportEngine._gather_inputs assembles them, and a generated report."""

from datetime import datetime, timezone
from typing import Any
from unittest.mock import AsyncMock, MagicMock

from app.api.v1.endpoints import compliance_reports
from app.core.permissions import Permissions
from app.models.compliance_report import ComplianceReport
from app.models.user import User
from app.repositories.compliance_report import ComplianceReportRepository
from app.schemas.compliance import EvaluationCoverage, InputCoverage, ReportFormat, ReportFramework, ReportStatus
from app.schemas.project import LicensePolicySchema
from app.services.analytics.scopes import ResolvedScope
from app.services.compliance.frameworks.base import EvaluationInput
from app.services.crypto_policy.seeder import seed_crypto_policies
from app.services.notifications.service import notification_service


def full_coverage(n_findings: int = 0, n_assets: int = 0) -> EvaluationCoverage:
    return EvaluationCoverage(
        findings=InputCoverage(evaluated=n_findings, in_scope=n_findings, limit=max(n_findings, 1)),
        crypto_assets=InputCoverage(evaluated=n_assets, in_scope=n_assets, limit=max(n_assets, 1)),
    )


def evaluation_input(**fields: Any) -> EvaluationInput:
    """An input over one user-scoped project; `coverage` defaults to every finding and asset read."""
    values: dict[str, Any] = {
        "resolved": ResolvedScope(scope="user", scope_id=None, project_ids=["p"]),
        "scope_description": "user",
        "crypto_assets": [],
        "findings": [],
        "policy_rules": [],
        "policy_version": 1,
        "iana_catalog_version": 1,
        "scan_ids": ["s1"],
        "override_version": None,
        "license_policy": LicensePolicySchema(),
        "db": MagicMock(),
        **fields,
    }
    values.setdefault("coverage", full_coverage(len(values["findings"]), len(values["crypto_assets"])))
    return EvaluationInput(**values)


async def generated_report(db: Any, monkeypatch: Any) -> ComplianceReport:
    """A project report requested by ``ownerp`` and generated by the engine, artifact included."""
    monkeypatch.setattr(notification_service, "notify_project_members", AsyncMock())
    await seed_crypto_policies(db)
    report = ComplianceReport(
        scope="project",
        scope_id="p",
        framework=ReportFramework.NIST_SP_800_131A,
        format=ReportFormat.JSON,
        status=ReportStatus.PENDING,
        requested_by="ownerp",
        requested_at=datetime.now(timezone.utc),
    )
    repo = ComplianceReportRepository(db)
    await repo.create(report)
    owner = User(id="ownerp", username="ownerp", email="ownerp@corp.com", permissions=[Permissions.PROJECT_READ])
    await compliance_reports._run_and_webhook(db, report, owner)
    generated = await repo.get_by_id(report.id)
    assert generated is not None
    return generated
