from .base import Analyzer
from .deps_dev import DepsDevAnalyzer
from .end_of_life import EndOfLifeAnalyzer
from .grype import GrypeAnalyzer
from .hash_verification import HashVerificationAnalyzer
from .license import LicenseAnalyzer
from .maintainer_risk import MaintainerRiskAnalyzer
from .malware import OpenSourceMalwareAnalyzer
from .osv import OSVAnalyzer
from .outdated import OutdatedAnalyzer
from .trivy import TrivyAnalyzer
from .typosquatting import TyposquattingAnalyzer
