name: Dependency Scan

on:
  push:
  pull_request:

jobs:
  scan-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft . -o json > sbom.json

      - name: Upload to Dependency Control
        env:
          # Configure these secrets in your GitHub Repository Settings
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          PROJECT_NAME: "your-project-name"
        run: |
          # Prepare JSON payload
          jq -n \
            --arg pn "$PROJECT_NAME" \
            --arg br "${{ github.ref_name }}" \
            --arg ch "${{ github.sha }}" \
            --arg pipeline_id "${{ github.run_id }}" \
            --arg pipeline_iid "${{ github.run_number }}" \
            --arg project_url "${{ github.server_url }}/${{ github.repository }}" \
            --arg project_path "${{ github.repository }}" \
            --arg default_branch "${{ github.event.repository.default_branch }}" \
            --slurpfile sbom sbom.json \
            '{
              project_name: $pn, 
              branch: $br, 
              commit_hash: $ch, 
              sboms: $sbom,
              metadata: {
                CI_PIPELINE_ID: ($pipeline_id | tonumber),
                CI_PIPELINE_IID: ($pipeline_iid | tonumber),
                CI_COMMIT_BRANCH: $br,
                CI_PROJECT_URL: $project_url,
                CI_PROJECT_PATH: $project_path,
                CI_DEFAULT_BRANCH: $default_branch,
                CI_JOB_STARTED_AT: (now | todate)
              }
            }' > payload.json

          # Send to Backend
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $DEP_CONTROL_API_KEY" \
            -d @payload.json \
            "$DEP_CONTROL_URL/api/v1/ingest"

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for TruffleHog to see history
      
      - name: Check Configuration
        id: check
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          SCANNER_NAME: "trufflehog"
        run: |
          AUTH_HEADER="x-api-key: $DEP_CONTROL_API_KEY"
          CONFIG=$(curl -s -H "$AUTH_HEADER" "$DEP_CONTROL_URL/api/v1/ingest/config")
          
          if echo "$CONFIG" | jq -e ".active_analyzers | index(\"$SCANNER_NAME\")" > /dev/null; then
            echo "Scanner $SCANNER_NAME is enabled."
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "Scanner $SCANNER_NAME is disabled."
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi

      - name: Install TruffleHog
        if: steps.check.outputs.enabled == 'true'
        run: curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          
      - name: Run TruffleHog
        if: steps.check.outputs.enabled == 'true'
        run: |
          # Run TruffleHog and output JSON. Exit code is ignored to process results manually.
          trufflehog git file://. --json > trufflehog.json || true
          
      - name: Upload Secrets to Dependency Control
        if: steps.check.outputs.enabled == 'true'
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          PROJECT_NAME: "your-project-name"
        run: |
          # Prepare JSON payload using jq
          jq -n \
            --arg pn "$PROJECT_NAME" \
            --arg br "${{ github.ref_name }}" \
            --arg ch "${{ github.sha }}" \
            --arg pipeline_id "${{ github.run_id }}" \
            --arg pipeline_iid "${{ github.run_number }}" \
            --arg project_url "${{ github.server_url }}/${{ github.repository }}" \
            --arg project_path "${{ github.repository }}" \
            --arg default_branch "${{ github.event.repository.default_branch }}" \
            --slurpfile findings trufflehog.json \
            '{
              project_name: $pn, 
              branch: $br, 
              commit_hash: $ch, 
              findings: $findings,
              metadata: {
                CI_PIPELINE_ID: ($pipeline_id | tonumber),
                CI_PIPELINE_IID: ($pipeline_iid | tonumber),
                CI_COMMIT_BRANCH: $br,
                CI_PROJECT_URL: $project_url,
                CI_PROJECT_PATH: $project_path,
                CI_DEFAULT_BRANCH: $default_branch,
                CI_JOB_STARTED_AT: (now | todate)
              }
            }' > payload.json
          
          # Send to Backend
          response=$(curl -s -X POST "$DEP_CONTROL_URL/api/v1/ingest/trufflehog" \
            -H "Content-Type: application/json" \
            -H "x-api-key: $DEP_CONTROL_API_KEY" \
            -d @payload.json)
            
          echo "Response: $response"
          
          # Fail if status is failed (unwaived secrets found)
          # Requires jq to be installed (standard on ubuntu-latest)
          status=$(echo $response | jq -r '.status')
          if [ "$status" == "failed" ]; then
            echo "CRITICAL: Unwaived secrets found!"
            exit 1
          fi

  opengrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Configuration
        id: check
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          SCANNER_NAME: "opengrep"
        run: |
          # Install jq/curl if missing
          if ! command -v jq &> /dev/null; then
             if [ -f /etc/alpine-release ]; then apk add --no-cache jq curl; else apt-get update && apt-get install -y jq curl; fi
          fi

          AUTH_HEADER="x-api-key: $DEP_CONTROL_API_KEY"
          CONFIG=$(curl -s -H "$AUTH_HEADER" "$DEP_CONTROL_URL/api/v1/ingest/config")
          
          if echo "$CONFIG" | jq -e ".active_analyzers | index(\"$SCANNER_NAME\")" > /dev/null; then
            echo "Scanner $SCANNER_NAME is enabled."
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "Scanner $SCANNER_NAME is disabled."
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run OpenGrep
        if: steps.check.outputs.enabled == 'true'
        run: semgrep scan --config=auto --json --output opengrep.json . || true
        
      - name: Upload SAST Results
        if: steps.check.outputs.enabled == 'true'
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          PROJECT_NAME: "your-project-name"
        run: |
          jq -n \
            --arg pn "$PROJECT_NAME" \
            --arg br "${{ github.ref_name }}" \
            --arg ch "${{ github.sha }}" \
            --slurpfile findings opengrep.json \
            '{project_name: $pn, branch: $br, commit_hash: $ch, findings: $findings[0].results}' > payload.json
            
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $DEP_CONTROL_API_KEY" \
            -d @payload.json \
            "$DEP_CONTROL_URL/api/v1/ingest/opengrep"

  kics-scan:
    runs-on: ubuntu-latest
    container:
      image: checkmarx/kics:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Configuration
        id: check
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          SCANNER_NAME: "kics"
        run: |
          # Install jq/curl if missing
          if ! command -v jq &> /dev/null; then
             apk add --no-cache jq curl
          fi

          AUTH_HEADER="x-api-key: $DEP_CONTROL_API_KEY"
          CONFIG=$(curl -s -H "$AUTH_HEADER" "$DEP_CONTROL_URL/api/v1/ingest/config")
          
          if echo "$CONFIG" | jq -e ".active_analyzers | index(\"$SCANNER_NAME\")" > /dev/null; then
            echo "Scanner $SCANNER_NAME is enabled."
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "Scanner $SCANNER_NAME is disabled."
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run KICS
        if: steps.check.outputs.enabled == 'true'
        run: |
          # Run KICS scan
          # --ignore-on-exit all ensures the step doesn't fail if vulnerabilities are found
          kics scan -p . -o . --output-name kics-results.json --report-formats json --ignore-on-exit all || true
        
      - name: Upload KICS Results
        if: steps.check.outputs.enabled == 'true'
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          PROJECT_NAME: "your-project-name"
        run: |
          # Prepare payload
          # KICS output structure needs to be passed correctly
          jq -n \
            --arg pn "$PROJECT_NAME" \
            --arg br "${{ github.ref_name }}" \
            --arg ch "${{ github.sha }}" \
            --slurpfile findings kics-results.json \
            '{project_name: $pn, branch: $br, commit_hash: $ch, queries: $findings[0].queries, files: $findings[0].files}' > payload.json
            
          # Send to Backend
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $DEP_CONTROL_API_KEY" \
            -d @payload.json \
            "$DEP_CONTROL_URL/api/v1/ingest/kics"

  bearer-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Configuration
        id: check
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          SCANNER_NAME: "bearer"
        run: |
          AUTH_HEADER="x-api-key: $DEP_CONTROL_API_KEY"
          CONFIG=$(curl -s -H "$AUTH_HEADER" "$DEP_CONTROL_URL/api/v1/ingest/config")
          
          if echo "$CONFIG" | jq -e ".active_analyzers | index(\"$SCANNER_NAME\")" > /dev/null; then
            echo "Scanner $SCANNER_NAME is enabled."
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "Scanner $SCANNER_NAME is disabled."
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install Bearer
        if: steps.check.outputs.enabled == 'true'
        run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        
      - name: Run Bearer
        if: steps.check.outputs.enabled == 'true'
        run: bearer scan . --format json --output bearer.json || true
        
      - name: Upload Bearer Results
        if: steps.check.outputs.enabled == 'true'
        env:
          DEP_CONTROL_URL: ${{ secrets.DEP_CONTROL_URL }}
          DEP_CONTROL_API_KEY: ${{ secrets.DEP_CONTROL_API_KEY }}
          PROJECT_NAME: "your-project-name"
        run: |
          jq -n \
            --arg pn "$PROJECT_NAME" \
            --arg br "${{ github.ref_name }}" \
            --arg ch "${{ github.sha }}" \
            --slurpfile findings bearer.json \
            '{project_name: $pn, branch: $br, commit_hash: $ch, findings: $findings[0]}' > payload.json
            
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $DEP_CONTROL_API_KEY" \
            -d @payload.json \
            "$DEP_CONTROL_URL/api/v1/ingest/bearer"

