stages:
  - dependency-scan

# ---------------------------------------------------------------------------
# Dependency Control GitLab CI/CD Example
# ---------------------------------------------------------------------------
# This pipeline demonstrates how to integrate with Dependency Control.
#
# Authentication Methods:
# 1. GitLab Integration (Recommended):
#    - Uses the automatic $CI_JOB_TOKEN.
#    - Requires "GitLab Integration" to be enabled in Dependency Control System Settings.
#    - Can automatically create projects and sync teams.
#
# 2. API Key (Legacy/Manual):
#    - Uses a static API Key generated in the Dependency Control Project Settings.
#    - Requires the DEP_CONTROL_API_KEY variable to be set in GitLab CI/CD Settings.
# ---------------------------------------------------------------------------

dependency-scan:
  stage: dependency-scan
  image: alpine:latest
  variables:
    # Configure these in your GitLab CI/CD Variables
    # DEP_CONTROL_URL: "https://your-dependency-control-instance.com"
    
    # Optional: Set if using API Key method
    # DEP_CONTROL_API_KEY: "your-project-api-key"
  before_script:
    - apk add --no-cache curl jq bash
    - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
  script:
    - echo "Generating SBOM..."
    - syft . -o json > sbom.json
    
    - echo "Preparing payload..."
    # We use CI_PROJECT_PATH (e.g. "group/project") as the project name
    - |
      jq -n         --arg pn "$CI_PROJECT_PATH"         --arg br "$CI_COMMIT_REF_NAME"         --arg ch "$CI_COMMIT_SHA"         --slurpfile sbom sbom.json         '{project_name: $pn, branch: $br, commit_hash: $ch, sbom: $sbom[0]}' > payload.json

    - echo "Sending to Dependency Control..."
    - |
      # Method 1: GitLab Integration (Recommended)
      if [ -z "$DEP_CONTROL_API_KEY" ]; then
        echo "Using GitLab CI Token..."
        curl -X POST           -H "Content-Type: application/json"           -H "JOB-TOKEN: $CI_JOB_TOKEN"           -d @payload.json           "$DEP_CONTROL_URL/api/v1/ingest"
      else
        # Method 2: API Key
        echo "Using API Key..."
        curl -X POST           -H "Content-Type: application/json"           -H "x-api-key: $DEP_CONTROL_API_KEY"           -d @payload.json           "$DEP_CONTROL_URL/api/v1/ingest"
      fi

secret-scan:
  stage: dependency-scan
  image: alpine:latest
  variables:
    # DEP_CONTROL_URL defined in CI/CD settings
  before_script:
    - apk add --no-cache curl jq bash git
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - echo "Running TruffleHog..."
    # TruffleHog needs git history
    - git fetch --unshallow || true
    - trufflehog git file://. --json > trufflehog.json || true
    
    - echo "Preparing payload..."
    - |
      echo '{"project_name": "'"$CI_PROJECT_PATH"'", "branch": "'"$CI_COMMIT_REF_NAME"'", "commit_hash": "'"$CI_COMMIT_SHA"'", "findings": [' > payload.json
      if [ -s trufflehog.json ]; then
        sed 's/$/,/' trufflehog.json | sed '$ s/,$//' >> payload.json
      fi
      echo ']}' >> payload.json
      
    - echo "Uploading results..."
    - |
      if [ -z "$DEP_CONTROL_API_KEY" ]; then
        # Method 1: GitLab Integration
        response=$(curl -s -X POST "$DEP_CONTROL_URL/api/v1/ingest/trufflehog"           -H "Content-Type: application/json"           -H "JOB-TOKEN: $CI_JOB_TOKEN"           -d @payload.json)
      else
        # Method 2: API Key
        response=$(curl -s -X POST "$DEP_CONTROL_URL/api/v1/ingest/trufflehog"           -H "Content-Type: application/json"           -H "x-api-key: $DEP_CONTROL_API_KEY"           -d @payload.json)
      fi
      
      echo "Response: $response"
      
      status=$(echo $response | jq -r '.status')
      if [ "$status" == "failed" ]; then
        echo "CRITICAL: Unwaived secrets found!"
        exit 1
      fi

opengrep-scan:
  stage: dependency-scan
  image: returntocorp/semgrep
  variables:
    # DEP_CONTROL_URL defined in CI/CD settings
  script:
    - echo "Running OpenGrep..."
    - semgrep scan --config=auto --json --output opengrep.json . || true
    
    # Install jq for payload formatting
    - if [ -f /etc/alpine-release ]; then apk add --no-cache jq curl; else apt-get update && apt-get install -y jq curl; fi
    
    - echo "Preparing payload..."
    - |
      jq -n         --arg pn "$CI_PROJECT_PATH"         --arg br "$CI_COMMIT_REF_NAME"         --arg ch "$CI_COMMIT_SHA"         --slurpfile findings opengrep.json         '{project_name: $pn, branch: $br, commit_hash: $ch, findings: $findings[0].results}' > payload.json
      
    - echo "Uploading results..."
    - |
      if [ -z "$DEP_CONTROL_API_KEY" ]; then
        # Method 1: GitLab Integration
        curl -X POST           -H "Content-Type: application/json"           -H "JOB-TOKEN: $CI_JOB_TOKEN"           -d @payload.json           "$DEP_CONTROL_URL/api/v1/ingest/opengrep"
      else
        # Method 2: API Key
        curl -X POST           -H "Content-Type: application/json"           -H "x-api-key: $DEP_CONTROL_API_KEY"           -d @payload.json           "$DEP_CONTROL_URL/api/v1/ingest/opengrep"
      fi
